using System.Text.Json;
using System.Text.Json.Serialization;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Archives;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Noggog;

namespace ENBLightToLightPlacer;

/// <summary>
/// Ports ENB particle-light meshes to Light Placer JSON.
///
/// Community Shaders has no particle-light reader -- Light Limit Fix's old
/// per-texture ini feature is gone from CS 26.x -- so every "ENB Light" /
/// "Particle Lights for ENB" mesh in a load order is inert. The meshes still
/// encode everything a light needs, and it maps onto Light Placer's schema:
///
///     marker quad's world position    -> points
///     vertex colour x emissive RGB    -> data.color
///     emissiveMultiple                -> data.fade
///     quad half-size x node scale     -> data.radius   (estimated)
///
/// Running as a Synthesis patcher buys three things a standalone script does
/// not get: the virtual Data folder resolves which mod wins each mesh path, so
/// there is no install-order parsing; archives are readable, so meshes inside
/// BSAs are not invisible; and the load order tells us which records use each
/// model, which bounds the work to meshes the game can actually show.
///
/// The output is a JSON file rather than records -- Light Placer's data cannot
/// be expressed as plugin records -- so the patch plugin itself stays empty.
/// </summary>
public class Program
{
    private static Lazy<Settings> _settings = null!;
    private static Settings Config => _settings.Value;

    public static Task<int> Main(string[] args)
    {
        // Detector parity check against tools/enblight2lp.py, which was
        // validated against CS Light's authored JSON. Runs without Mutagen or
        // a load order, so it is the cheap way to confirm a NIF-reading change
        // did not silently move a colour or a point.
        if (args.Length > 1 && args[0] == "--selftest")
            return Task.FromResult(SelfTest(args[1..]));

        // Archive round-trip check: resolve Data-relative paths the way the
        // patcher does, against a real Data folder. The archive folder/file
        // addressing is the part most likely to be subtly wrong.
        if (args.Length > 2 && args[0] == "--selftest-assets")
            return Task.FromResult(SelfTestAssets(args[1], args[2..]));

        return SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "ENBLightToLightPlacer.esp")
            .Run(args);
    }

    private static int SelfTest(string[] paths)
    {
        foreach (var path in paths)
        {
            Console.WriteLine($"===== {path}");
            if (!File.Exists(path)) { Console.WriteLine("  missing"); continue; }
            var probe = new Nif(File.ReadAllBytes(path));
            Console.WriteLine($"  blocks={probe.BlockCount} bsver={probe.BsVersion} strings={probe.Strings.Count}");
            foreach (var s in probe.ReadShapes())
                Console.WriteLine($"    shape[{s.Index}] {s.Name} verts={s.Verts.Count} "
                                  + $"colors={s.Colors.Count} shaderRef={s.ShaderRef} "
                                  + $"shaderType={(s.ShaderRef >= 0 && s.ShaderRef < probe.BlockCount ? probe.BlockType(s.ShaderRef) : "-")}");
            foreach (var m in MarkerDetector.Find(probe))
            {
                Console.WriteLine(
                    $"  node={m.NodeName} tex={m.Texture} colour=({string.Join(',', m.Color)}) "
                    + $"fade={m.Fade} point=({string.Join(',', m.Point)}) half={m.HalfSize}"
                    + (m.Note.Length > 0 ? $" [{m.Note}]" : ""));
            }
        }
        return 0;
    }

    private static int SelfTestAssets(string dataFolder, string[] relativePaths)
    {
        var assets = new AssetResolver(GameRelease.SkyrimSE, new DirectoryPath(dataFolder));
        foreach (var rel in relativePaths)
        {
            var bytes = assets.Read(rel);
            if (bytes == null) { Console.WriteLine($"  MISS {rel}"); continue; }
            var markers = MarkerDetector.Find(new Nif(bytes));
            Console.WriteLine($"  ok   {rel}  {bytes.Length} bytes, {markers.Count} marker(s)");
            foreach (var m in markers)
                Console.WriteLine($"         colour=({string.Join(',', m.Color)}) fade={m.Fade} "
                                  + $"point=({string.Join(',', m.Point)}) half={m.HalfSize}");
        }
        return 0;
    }

    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var models = CollectModelPaths(state);
        Console.WriteLine($"{models.Count} distinct model paths referenced by records");

        var assets = new AssetResolver(state.GameRelease, state.DataFolderPath);
        var entries = new List<LightEntry>();
        int read = 0, withMarker = 0, flagged = 0;

        foreach (var model in models.OrderBy(m => m, StringComparer.OrdinalIgnoreCase))
        {
            if (Config.SkipActorMeshes && model.StartsWith(@"actors\", StringComparison.OrdinalIgnoreCase))
                continue;
            if (Config.ExcludePathsContaining.Any(x =>
                    x.Length > 0 && model.Contains(x, StringComparison.OrdinalIgnoreCase)))
                continue;

            var bytes = assets.Read(Path.Combine("meshes", model));
            if (bytes == null) continue;
            read++;

            List<Marker> markers;
            try { markers = MarkerDetector.Find(new Nif(bytes)); }
            catch (Exception ex)
            {
                Console.WriteLine($"  ! {model}: {ex.GetType().Name}");
                continue;
            }
            if (markers.Count == 0) continue;
            withMarker++;

            var lights = new List<Light>();
            foreach (var marker in markers)
            {
                // A marker with no extent gives a zero-radius light: an entry that
                // costs a light slot and illuminates nothing.
                if (marker.HalfSize <= 0)
                {
                    Console.WriteLine($"  ~ {model}: marker has no extent, skipped");
                    continue;
                }
                if (marker.Note.Length > 0)
                {
                    flagged++;
                    Console.WriteLine($"  ? {model}: {marker.Note}, colour {string.Join(',', marker.Color)}");
                }

                float radius = EstimateRadius(marker.HalfSize);
                float fade = marker.Fade;
                var rule = Config.Overrides.FirstOrDefault(o =>
                    o.PathContains.Length > 0 &&
                    model.Contains(o.PathContains, StringComparison.OrdinalIgnoreCase));
                if (rule != null)
                {
                    if (rule.Radius > 0) radius = rule.Radius;
                    if (rule.Fade > 0) fade = rule.Fade;
                }

                lights.Add(new Light
                {
                    Data = new LightData
                    {
                        Light = Config.LightTemplate,
                        Color = marker.Color,
                        Fade = MathF.Round(fade, 3),
                        Radius = MathF.Round(radius, 1),
                        Flags = Config.LightFlags,
                    },
                    Points = [marker.Point],
                });
            }

            if (lights.Count == 0) continue;
            entries.Add(new LightEntry { Lights = lights, Models = [model] });
            Console.WriteLine($"  + {model}  ({lights.Count} light{(lights.Count == 1 ? "" : "s")})");
        }

        // Meshes the ENB mods never patched, borrowing a light from the mesh that
        // is the same object. See Settings.Aliases.
        var byModel = entries.ToDictionary(e => e.Models[0], StringComparer.OrdinalIgnoreCase);
        foreach (var alias in Config.Aliases)
        {
            if (alias.Target.Length == 0 || alias.Source.Length == 0) continue;
            if (byModel.ContainsKey(alias.Target)) continue;
            if (!byModel.TryGetValue(alias.Source, out var source))
            {
                Console.WriteLine($"  ~ alias {alias.Target}: source {alias.Source} produced no light");
                continue;
            }
            entries.Add(new LightEntry
            {
                Lights = source.Lights.Select(l => new Light
                {
                    Data = new LightData
                    {
                        Light = l.Data.Light,
                        Color = (int[])l.Data.Color.Clone(),
                        Fade = l.Data.Fade,
                        Radius = l.Data.Radius,
                        Flags = l.Data.Flags,
                    },
                    Points = l.Points.Select(pt => (float[])pt.Clone()).ToList(),
                }).ToList(),
                Models = [alias.Target.ToLowerInvariant()],
            });
            Console.WriteLine($"  + {alias.Target}  (alias of {alias.Source})");
        }

        Console.WriteLine();
        Console.WriteLine($"read {read} meshes, {withMarker} carried an ENB marker, "
                          + $"{entries.Sum(e => e.Lights.Count)} lights, {flagged} flagged for review");

        WriteJson(state, entries);
    }

    private static float EstimateRadius(float half)
    {
        if (half <= 0) return 0;
        var estimate = Config.RadiusBase
                       * MathF.Pow(half / Config.RadiusReferenceHalfSize, Config.RadiusExponent);
        return Config.MaxEstimatedRadius > 0
            ? MathF.Min(estimate, Config.MaxEstimatedRadius)
            : estimate;
    }

    /// <summary>Every model path any record points at, deduplicated.</summary>
    private static HashSet<string> CollectModelPaths(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var models = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var rec in state.LoadOrder.PriorityOrder.WinningOverrides<ISkyrimMajorRecordGetter>())
        {
            if (rec is not IModeledGetter modeled) continue;
            var file = modeled.Model?.File.ToString();
            if (string.IsNullOrWhiteSpace(file)) continue;
            var clean = file.Replace('/', '\\').TrimStart('\\');
            if (clean.StartsWith(@"meshes\", StringComparison.OrdinalIgnoreCase))
                clean = clean[7..];
            if (clean.EndsWith(".nif", StringComparison.OrdinalIgnoreCase))
                models.Add(clean.ToLowerInvariant());
        }
        return models;
    }

    private static void WriteJson(
        IPatcherState<ISkyrimMod, ISkyrimModGetter> state, List<LightEntry> entries)
    {
        // Against the Data folder, not the plugin's folder: Synthesis copies only
        // the .esp out of its staging workspace, so anything written beside the
        // plugin is stranded in a temp directory. Under MO2 this lands in Overwrite.
        var target = Path.Combine(state.DataFolderPath.Path, Config.OutputJsonPath);
        Directory.CreateDirectory(Path.GetDirectoryName(target)!);

        var json = JsonSerializer.Serialize(entries, new JsonSerializerOptions
        {
            WriteIndented = true,
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        });
        // No BOM: Light Placer's parser wants plain UTF-8.
        File.WriteAllText(target, json + Environment.NewLine, new System.Text.UTF8Encoding(false));
        Console.WriteLine($"wrote {entries.Count} entries to {target}");
    }

    // ------------------------------------------------------------- json shape

    private sealed class LightEntry
    {
        [JsonPropertyName("lights")] public List<Light> Lights { get; set; } = [];
        [JsonPropertyName("models")] public List<string> Models { get; set; } = [];
    }

    private sealed class Light
    {
        [JsonPropertyName("data")] public LightData Data { get; set; } = new();
        [JsonPropertyName("points")] public List<float[]> Points { get; set; } = [];
    }

    private sealed class LightData
    {
        [JsonPropertyName("light")] public string Light { get; set; } = "";
        [JsonPropertyName("color")] public int[] Color { get; set; } = [];
        [JsonPropertyName("fade")] public float Fade { get; set; }
        [JsonPropertyName("radius")] public float Radius { get; set; }
        [JsonPropertyName("flags")] public string Flags { get; set; } = "";
    }
}

/// <summary>
/// Reads a Data-relative file, loose first then archives. Loose has to win --
/// that is the order the game resolves in, and it is how a mod's patched mesh
/// beats the vanilla BSA copy.
/// </summary>
public sealed class AssetResolver
{
    private readonly DirectoryPath _dataFolder;
    private readonly List<IArchiveReader> _readers = [];

    public AssetResolver(GameRelease release, DirectoryPath dataFolder)
    {
        _dataFolder = dataFolder;

        // Every .bsa physically present, rather than Archive.GetApplicableArchivePaths.
        // That helper resolves the base game's archives through the INI's
        // sResourceArchiveList, which under MO2 lives in the profile and is not
        // what a patcher process necessarily reads -- outside MO2 it returned 5
        // Creation Club archives and none of Skyrim - Meshes0/1.bsa. Under the
        // VFS the Data folder already shows exactly the archives of enabled mods,
        // so enumerating it is both simpler and more faithful.
        foreach (var path in Directory.EnumerateFiles(_dataFolder.Path, "*.bsa"))
        {
            try { _readers.Add(Archive.CreateReader(release, new FilePath(path))); }
            catch (Exception ex) { Console.WriteLine($"  ! archive {path}: {ex.GetType().Name}"); }
        }
        Console.WriteLine($"{_readers.Count} archives open, data folder {_dataFolder}");
    }

    public byte[]? Read(string dataRelativePath)
    {
        var loose = Path.Combine(_dataFolder.Path, dataRelativePath);
        if (File.Exists(loose))
        {
            try { return File.ReadAllBytes(loose); }
            catch { return null; }
        }

        // Archives are addressed folder-then-file, not by whole path.
        var folderPath = Path.GetDirectoryName(dataRelativePath) ?? string.Empty;
        var fileName = Path.GetFileName(dataRelativePath);

        foreach (var reader in _readers)
        {
            try
            {
                if (!reader.TryGetFolder(folderPath, out var folder)) continue;
                foreach (var file in folder.Files)
                {
                    if (!Path.GetFileName(file.Path).Equals(fileName, StringComparison.OrdinalIgnoreCase))
                        continue;
                    return file.GetBytes().ToArray();
                }
            }
            catch { /* a malformed archive is not worth aborting the run for */ }
        }
        return null;
    }
}
